#████████╗██╗███╗░░░███╗░█████╗░  ███████╗░█████╗░██╗░░██╗███████╗  ░█████╗░███╗░░██╗██╗░░░░░██╗███╗░░██╗███████╗
#╚══██╔══╝██║████╗░████║██╔══██╗  ██╔════╝██╔══██╗██║░██╔╝██╔════╝  ██╔══██╗████╗░██║██║░░░░░██║████╗░██║██╔════╝
#░░░██║░░░██║██╔████╔██║███████║  █████╗░░███████║█████═╝░█████╗░░  ██║░░██║██╔██╗██║██║░░░░░██║██╔██╗██║█████╗░░
#░░░██║░░░██║██║╚██╔╝██║██╔══██║  ██╔══╝░░██╔══██║██╔═██╗░██╔══╝░░  ██║░░██║██║╚████║██║░░░░░██║██║╚████║██╔══╝░░
#░░░██║░░░██║██║░╚═╝░██║██║░░██║  ██║░░░░░██║░░██║██║░╚██╗███████╗  ╚█████╔╝██║░╚███║███████╗██║██║░╚███║███████╗
#░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝  ╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝  ░╚════╝░╚═╝░░╚══╝╚══════╝╚═╝╚═╝░░╚══╝╚══════╝
#
#plugin by Timur Rootkovskiy (Adminov)
#vk - @timurroot
#site - www.rootkovskiy.ovh
#pls use \n to indent
#
noperm: "у вас нет прав"
usage: "надо вот так: /tfo <ON/OFF>"
#
on_message: "вы включили фейковый онлайн"
off_message: "вы выключили фейковый онлайн"
#
#online multiplier
multiplier: 2